coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
